<?php
/**
 * Created by PhpStorm.
 * User: bpds
 * Date: 13/07/15
 * Time: 10:37
 */
require_once 'GenerativeHelper.php';

class GenerativeHelperForPhp extends GenerativeHelper {

    static function defaultHeader(Flexed $f, $d) {
        $header = "
/**
* Generated by Flexions for $f->author on ?
* https://github.com/benoit-pereira-da-silva/Flexions/
";
        $willBePreserved=GenerativeHelper::flexedWillBePreserved($f);
        if ($willBePreserved==false){
            // We distinguish files that are generated once from "re-generable files"
            $header.= "*
* DO NOT MODIFY THIS FILE YOUR MODIFICATIONS WOULD BE ERASED ON NEXT GENERATION!
* IF NECESSARY YOU CAN MARK THIS FILE TO BE PRESERVED
* IN THE PREPROCESSOR BY ADDING IN Hypotypose::instance().preservePath
";
        }
$header.="*
* Copyright (c) 2015  $f->company  All rights reserved.
*/
";
        return $header;

    }


}