//
//  User.swift
//  Swagger-Sample
//
//  Generated by Flexions for benoit@pereira-da-silva.com on ?
//  https://github.com/benoit-pereira-da-silva/Flexions
//
// DO NOT MODIFY THIS FILE YOUR MODIFICATIONS WOULD BE ERASED ON NEXT GENERATION!
// IF NECESSARY YOU CAN MARK THIS FILE TO BE PRESERVED
// IN THE PREPROCESSOR BY ADDING IN Hypotypose::instance().preservePath
//
// Copyright (c) 2015  Chaosmos  All rights reserved.
//

@class User:NSObject,NSCoding,Mappable{

	var id:Integer?
	var username:String?
	var firstName:String?
	var lastName:String?
	var email:String?
	var password:String?
	var phone:String?
	var userStatus:Integer?


    // MARK: NSCoding

    required init(coder decoder: NSCoder!) {
        //array = decoder.decodeObjectForKey("array") as? [String]
    }

    func encodeWithCoder(aCoder: NSCoder!) {
        aCoder.encodeObject(self.array, forKey: "array")
    }

    // MARK: Mappable

    required init?(map: Map) {
        mapping(map)
    }

    func mapping(_ map: Map) {
		id<-["id"]
		username<-["username"]
		firstName<-["firstName"]
		lastName<-["lastName"]
		email<-["email"]
		password<-["password"]
		phone<-["phone"]
		userStatus<-["userStatus"]
    }


}