<?php
/**
* Generated by Flexions for flexions@pereira-da-silva.com on ?
* https://github.com/benoit-pereira-da-silva/Flexions/
*
* Copyright (c) 2015  COMPANY  All rights reserved.
*/
require_once "/endpoints/PetEndPoint.class.php";
require_once "/endpoints/PetFindByStatusEndPoint.class.php";
require_once "/endpoints/PetFindByTagsEndPoint.class.php";
require_once "/endpoints/PetWithPetIdEndPoint.class.php";
require_once "/endpoints/PetWithPetIdUploadImageEndPoint.class.php";
require_once "/endpoints/StoreInventoryEndPoint.class.php";
require_once "/endpoints/StoreOrderEndPoint.class.php";
require_once "/endpoints/StoreOrderWithOrderIdEndPoint.class.php";
require_once "/endpoints/UserEndPoint.class.php";
require_once "/endpoints/UserCreateWithArrayEndPoint.class.php";
require_once "/endpoints/UserCreateWithListEndPoint.class.php";
require_once "/endpoints/UserLoginEndPoint.class.php";
require_once "/endpoints/UserLogoutEndPoint.class.php";
require_once "/endpoints/UserWithUsernameEndPoint.class.php";
?>


