<?php
/**
* Generated by Flexions for flexions@pereira-da-silva.com on ?
* https://github.com/benoit-pereira-da-silva/Flexions/
*
* DO NOT MODIFY THIS FILE YOUR MODIFICATIONS WOULD BE ERASED ON NEXT GENERATION!
* IF NECESSARY YOU CAN MARK THIS FILE TO BE PRESERVED
* IN THE PREPROCESSOR BY ADDING IN Hypotypose::instance().preservePath
*
* Copyright (c) 2015  COMPANY  All rights reserved.
*/

class StoreOrderEndPoint{
}
?>
